/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./projects/composite/src/**/*.{html,ts}"],
  safelist: [
    // Dynamic classes used by comp-button component
    "bg-blue-500",
    "bg-blue-400",
    "hover:bg-blue-400",
    "hover:bg-blue-500",
    "bg-red-500",
    "bg-red-400",
    "hover:bg-red-400",
    "hover:bg-red-500",
    "bg-green-500",
    "bg-green-400",
    "hover:bg-green-400",
    "hover:bg-green-500",
    "text-blue-500",
    "text-blue-400",
    "hover:text-blue-400",
    "hover:text-blue-500",
    "text-red-500",
    "text-red-400",
    "hover:text-red-400",
    "hover:text-red-500",
    "text-green-500",
    "text-green-400",
    "hover:text-green-400",
    "hover:text-green-500",
    "border-blue-500",
    "border-blue-400",
    "hover:border-blue-400",
    "hover:border-blue-500",
    "border-red-500",
    "border-red-400",
    "hover:border-red-400",
    "hover:border-red-500",
    "border-green-500",
    "border-green-400",
    "hover:border-green-400",
    "hover:border-green-500",
    "px-4",
    "py-2",
    "rounded-lg",
    "cursor-pointer",
    "border",
    "border-2",
    "hover:border",
    "hover:border-2",
    "text-white",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
